apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  namespace: ue1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 2 
  template: 
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: sharepointoscar/skiapp:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"