apiVersion: v1
kind: Service
metadata:
  name: app1-service-ue1
  namespace: ue1
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: app1-ue1
